# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  user: postgres
  timeout: 5000
  password: p0stgr3s
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portal_client_development

test:
  <<: *default
  database: portal_client_test

sandbox:
  <<: *default
  database: portal_client_sandbox

production:
  <<: *default
  host: localhost
  database: portal_client_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
